name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            git config --global credential.helper store
            if [ ! -d "/opt/autodeploy/.git" ]; then
              echo "https://${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}@github.com/feniuspw/autodeploy.git"
              git clone https://${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}@github.com/feniuspw/autodeploy.git /opt/autodeploy
            fi
            cd /opt/autodeploy
            git pull origin main
